# 创建Tensor
`torch.empty(size())` 初始化空的张量  
`torch.zeros(size())` 初始化为0的张量  
`torch.ones(size())` 初始化为1的张量  
`torch.rand(size())` 随机初始化的张量  
`torch.randn(size())` 标准正态分布的随机张量  

In [1]:
import torch
torch.empty(3,5)

tensor([[9.2755e-39, 1.0286e-38, 9.0919e-39, 8.9082e-39, 9.2755e-39],
        [8.4490e-39, 1.0194e-38, 9.0919e-39, 8.4490e-39, 1.0561e-38],
        [1.0194e-38, 8.9082e-39, 9.2755e-39, 9.1837e-39, 9.0919e-39]])

In [14]:
torch.zeros(5,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [4]:
x=torch.ones(5,3)

In [5]:
torch.rand(5,3)

tensor([[0.6472, 0.0934, 0.8582],
        [0.9830, 0.0917, 0.3626],
        [0.3101, 0.4578, 0.0247],
        [0.1838, 0.1024, 0.1453],
        [0.0655, 0.7149, 0.0367]])

In [6]:
torch.zeros(5,3,dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
torch.tensor([3.3,2])

tensor([3.3000, 2.0000])

**还可以通过现有的Tensor来创建，此方法会默认重用输入Tensor的一些属性，例如数据类型，除非自定义数据类型**

In [15]:
x = x.new_ones(5,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [19]:
x = torch.randn_like(x,dtype=torch.float32)
print(x)

tensor([[-1.8926, -0.5262,  0.7685],
        [ 1.0225,  0.9823, -1.5601],
        [ 0.6045,  0.4192, -0.5953],
        [-0.8541,  1.0707, -1.4721],
        [-1.6028,  0.7895,  0.0504]])


In [20]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [22]:
x.view(3,5)

tensor([[-1.8926, -0.5262,  0.7685,  1.0225,  0.9823],
        [-1.5601,  0.6045,  0.4192, -0.5953, -0.8541],
        [ 1.0707, -1.4721, -1.6028,  0.7895,  0.0504]])

In [30]:
torch.eye(5,7)


tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [34]:
torch.arange(3,10,2)


tensor([3, 5, 7, 9])

In [32]:
torch.linspace(3,10,5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [43]:
torch.randperm(10,dtype=torch.float)

tensor([6., 5., 3., 1., 4., 8., 7., 0., 2., 9.])

In [47]:
torch.arange(1, 0, -0.1)

tensor([1.0000, 0.9000, 0.8000, 0.7000, 0.6000, 0.5000, 0.4000, 0.3000, 0.2000,
        0.1000])

In [48]:
torch.arange(1., 11.)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([0.6807, 1.9861, 2.2647, 4.6975, 5.2237, 4.9490, 7.0439, 7.7013, 9.2735,
        9.8889])